model:
  name: "unsloth/DeepSeek-R1-32B"
  max_seq_length: 2048
  load_in_4bit: true
  dtype: "float16"

peft:
  r: 16
  lora_alpha: 16
  lora_dropout: 0.05
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]

training:
  output_dir: "./deepseek_r1_finetuned"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 2
  learning_rate: 2e-5
  logging_steps: 50
  save_steps: 500
  evaluation_strategy: "steps"
  fp16: true
  push_to_hub: false